# specify language
language:
  - python

# specify python versions
python:
  - "2.6"
  - "2.7"

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - python tests.py