# specify language
language:
  - python

# specify python versions
python:
  - "2.6"
  - "2.7"

# install dependencies
install:
  - npm install bower
  - pip install -r requirements.txt
  - bower install

# run tests
script:
  - python tests.py